//
// File generated by rootcint at Fri Jul  6 01:04:07 2018

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME h2root_funcDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "h2root_funcDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

/********************************************************
* h2root_funcDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableh2root_funcDict();

extern "C" void G__set_cpp_environmenth2root_funcDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("h2root_func.h");
  G__cpp_reset_tagtableh2root_funcDict();
}
#include <new>
extern "C" int G__cpp_dllrevh2root_funcDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */
static int G__h2root_funcDict__0_2180(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) init_h2root());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__h2root_funcDict__0_2181(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) open_file((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__h2root_funcDict__0_2182(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      convert_directory_shm();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__h2root_funcDict__0_2183(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      convert_directory((const Int_t) G__int(libp->para[0]), (TDirectoryFile*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__h2root_funcDict__0_2184(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      convert_1d((Int_t) G__int(libp->para[0]), (TDirectoryFile*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__h2root_funcDict__0_2185(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      convert_2d((Int_t) G__int(libp->para[0]), (TDirectoryFile*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__h2root_funcDict__0_2186(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      convert_profile((Int_t) G__int(libp->para[0]), (TDirectoryFile*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__h2root_funcDict__0_2187(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      convert_rwn((Int_t) G__int(libp->para[0]), (TDirectoryFile*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__h2root_funcDict__0_2188(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      convert_cwn((Int_t) G__int(libp->para[0]), (TDirectoryFile*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunch2root_funcDict {
 public:
  G__Sizep2memfunch2root_funcDict(): p(&G__Sizep2memfunch2root_funcDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunch2root_funcDict::*p)();
};

size_t G__get_sizep2memfunch2root_funcDict()
{
  G__Sizep2memfunch2root_funcDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceh2root_funcDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableh2root_funcDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__h2root_funcDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__h2root_funcDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__h2root_funcDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__h2root_funcDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__h2root_funcDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__h2root_funcDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__h2root_funcDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__h2root_funcDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__h2root_funcDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__h2root_funcDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarh2root_funcDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunch2root_funcDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalh2root_funcDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
   G__memfunc_setup("init_h2root", 1137, G__h2root_funcDict__0_2180, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("open_file", 945, G__h2root_funcDict__0_2181, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("convert_directory_shm", 2268, G__h2root_funcDict__0_2182, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("convert_directory", 1845, G__h2root_funcDict__0_2183, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 10 - - U 'TDirectoryFile' - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("convert_1d", 1013, G__h2root_funcDict__0_2184, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - - U 'TDirectoryFile' - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("convert_2d", 1014, G__h2root_funcDict__0_2185, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - - U 'TDirectoryFile' - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("convert_profile", 1617, G__h2root_funcDict__0_2186, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - - U 'TDirectoryFile' - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("convert_rwn", 1207, G__h2root_funcDict__0_2187, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - - U 'TDirectoryFile' - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("convert_cwn", 1192, G__h2root_funcDict__0_2188, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - - U 'TDirectoryFile' - 0 - -", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funch2root_funcDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__h2root_funcDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__h2root_funcDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__h2root_funcDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__h2root_funcDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__h2root_funcDictLN_TDirectoryFile = { "TDirectoryFile" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableh2root_funcDict() {
  G__h2root_funcDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__h2root_funcDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__h2root_funcDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__h2root_funcDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__h2root_funcDictLN_TDirectoryFile.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableh2root_funcDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__h2root_funcDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__h2root_funcDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__h2root_funcDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__h2root_funcDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__h2root_funcDictLN_TDirectoryFile);
}
extern "C" void G__cpp_setuph2root_funcDict(void) {
  G__check_setup_version(30051515,"G__cpp_setuph2root_funcDict()");
  G__set_cpp_environmenth2root_funcDict();
  G__cpp_setup_tagtableh2root_funcDict();

  G__cpp_setup_inheritanceh2root_funcDict();

  G__cpp_setup_typetableh2root_funcDict();

  G__cpp_setup_memvarh2root_funcDict();

  G__cpp_setup_memfunch2root_funcDict();
  G__cpp_setup_globalh2root_funcDict();
  G__cpp_setup_funch2root_funcDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunch2root_funcDict();
  return;
}
class G__cpp_setup_inith2root_funcDict {
  public:
    G__cpp_setup_inith2root_funcDict() { G__add_setup_func("h2root_funcDict",(G__incsetup)(&G__cpp_setuph2root_funcDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_inith2root_funcDict() { G__remove_setup_func("h2root_funcDict"); }
};
G__cpp_setup_inith2root_funcDict G__cpp_setup_initializerh2root_funcDict;

