/********************************************************************
* h2root_funcDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error h2root_funcDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableh2root_funcDict();
extern void G__cpp_setup_inheritanceh2root_funcDict();
extern void G__cpp_setup_typetableh2root_funcDict();
extern void G__cpp_setup_memvarh2root_funcDict();
extern void G__cpp_setup_globalh2root_funcDict();
extern void G__cpp_setup_memfunch2root_funcDict();
extern void G__cpp_setup_funch2root_funcDict();
extern void G__set_cpp_environmenth2root_funcDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "h2root_func.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__h2root_funcDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__h2root_funcDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__h2root_funcDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__h2root_funcDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__h2root_funcDictLN_TDirectoryFile;

/* STUB derived class for protected member access */
