/********************************************************************
* MyTFileDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MyTFileDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMyTFileDict();
extern void G__cpp_setup_inheritanceMyTFileDict();
extern void G__cpp_setup_typetableMyTFileDict();
extern void G__cpp_setup_memvarMyTFileDict();
extern void G__cpp_setup_globalMyTFileDict();
extern void G__cpp_setup_memfuncMyTFileDict();
extern void G__cpp_setup_funcMyTFileDict();
extern void G__set_cpp_environmentMyTFileDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MyTFile.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MyTFileDictLN_TClass;
extern G__linked_taginfo G__MyTFileDictLN_TBuffer;
extern G__linked_taginfo G__MyTFileDictLN_TDirectory;
extern G__linked_taginfo G__MyTFileDictLN_TMemberInspector;
extern G__linked_taginfo G__MyTFileDictLN_TObject;
extern G__linked_taginfo G__MyTFileDictLN_TNamed;
extern G__linked_taginfo G__MyTFileDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MyTFileDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyTFileDictLN_TTimer;
extern G__linked_taginfo G__MyTFileDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MyTFileDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyTFileDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MyTFileDictLN_TFile;
extern G__linked_taginfo G__MyTFileDictLN_TDirectoryFile;
extern G__linked_taginfo G__MyTFileDictLN_MyTFile;

/* STUB derived class for protected member access */
